// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [{ type: 'autogenerated', dirName: 'intro' }],
  developmentSidebar: [{ type: 'autogenerated', dirName: 'development' }],
};

export default sidebars;
